First commit
htmlacademy-ecmascript/1452537-big-trip-14 pull request #4
Opened 2021-04-26 20:38 UTC by Nikulichka

Не совсем поняла задание, сделала что мне захотелось. 
Форма добавления точки открывается при нажатии на кнопку New event. 
Форма редактирования при нажатии на треугольник точки. 
Закрываются на Esc только(пока что). 
Даты не по техзаданию, чтобы можно было смотреть сортировку. 
Не поняла, что за логику надо было описать в шаблоне редактирования: "Обратите внимание на условия поведения того или иного элемента формы, условия описаны в техническом задании." 
А ещё непонятно: "Для оставшихся компонентов также перепишите функцию по созданию шаблона, чтобы она на вход принимала данные." - для каких еще компонентов?
А ещё, не знаю правильно или нет - точки, форма добавления и форма редактирования отрисовываются от 1 структуры данных. Форма добавления на основе 0 элемента, форма редактирования на основе 1 элемента, все остальные - точки.

2021-04-29 06:13 UTC, Dima-Dim requested changes
Сейчас при открытии карточки на редактирование у нас появляется рядом новая карточка, вместо изменения состояния новой. Но на данном этапе редактирование реализовывать и не нужно. Вы ещё не знаете, как это делать правильно.
Сейчас в main.js довольно иного каких-то конкретных моментов, которые можно размести по соответствующим файлам.

В целом нужно навести порядок в файлах и не бежать вперёд задания :)

2021-04-29 06:13 UTC, Dima-Dim commented on src/view/add-point.js
> +export const createPointTypesTemplate = (currentType) => {
Файл называется add-point, значит экспортироваться из него должна только createAddPointTemplate. Так же тут могут быть какие-то вспомогательные функции для неё. Для всего остального нужно создать отдельные файлы с соответствующими названиями.

2021-04-29 06:13 UTC, Dima-Dim commented on src/view/no-point.js
> +const createEmptyListTemplate = () => {
Тут нужно привести в соответствие название экспортируемой функции и название файла.

2021-04-29 06:13 UTC, Dima-Dim commented on src/view/point-list.js
> +const createPointListTemplate = () => {
Вот пример где всё корректно :)

2021-04-29 06:13 UTC, Dima-Dim commented on src/view/route-info.js
> +const renderDestinations = (dest) => {
Довольно странное название для функции которая ничего не рендерит :)

2021-04-29 06:26 UTC, Nikulichka commented on src/view/point-list.js
> +const createPointListTemplate = () => {
ок)

2021-04-30 03:16 UTC, Dima-Dim commented on src/main.js
> +    const filtredPoints = sortingDatePointsSlice.filter((e) =>
Вместо `e` лучше так же использовать что-то более осмысленное.

2021-04-30 03:16 UTC, Dima-Dim commented on src/main.js
> +  filterElement.addEventListener('change', () => {
Довольно большая функция в `addEventListener`, такие лучше выносить в отдельные переменные чтобы улучшить читаемость кода.

2021-04-30 03:16 UTC, merged